# Generated by Django 3.2 on 2021-05-03 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devdoot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemreport',
            name='reported_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devdoot.publicproblem'),
        ),
        migrations.AlterField(
            model_name='problemreport',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devdoot.extendeduser'),
        ),
    ]
