# Generated by Django 3.2 on 2021-05-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devdoot', '0002_auto_20210504_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemtype',
            name='problem_title_h',
            field=models.CharField(default=models.CharField(max_length=120), max_length=120),
        ),
        migrations.AddField(
            model_name='problemtype',
            name='problem_title_m',
            field=models.CharField(default=models.CharField(max_length=120), max_length=120),
        ),
        migrations.AlterField(
            model_name='problemtype',
            name='problem_title',
            field=models.CharField(max_length=120),
        ),
    ]
