# Generated by Django 3.2 on 2021-05-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devdoot', '0003_auto_20210504_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemtype',
            name='problem_title_h',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='problemtype',
            name='problem_title_m',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
    ]
