# Generated by Django 3.2 on 2021-05-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devdoot', '0004_auto_20210504_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicproblem',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='publicproblem',
            name='last_name',
        ),
    ]
