# Generated by Django 3.2 on 2021-05-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devdoot', '0005_auto_20210505_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='group_name',
            field=models.CharField(blank=True, default='None', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='problem_types',
            field=models.CharField(blank=True, default='None', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='address',
            field=models.CharField(blank=True, default='None', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='profession',
            field=models.CharField(blank=True, default='None', max_length=60, null=True),
        ),
    ]
