# Generated by Django 3.2 on 2021-05-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devdoot', '0006_auto_20210507_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='problem_types',
            field=models.TextField(blank=True, default='None', max_length=1000, null=True),
        ),
    ]
